package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/nstranquist/docs-puller/searchruntime"
)

// extract is the family of code-aware ingestion modes — they walk source
// trees, synthesize markdown describing what's there, and feed that synthetic
// output through the same ingest plumbing the markdown crawlers use.
//
// Today the only kind is "sql-schema": SQL migrations → one markdown doc per
// migration file with the original DDL fenced and a "Tables touched" header
// extracted from CREATE/ALTER/CREATE POLICY statements. This makes migrations
// findable by table name and policy name in the FTS index without dumping
// every .sql byte into source files.
//
// Output lands under <source>/_schema/migrations/<basename>.md so search
// filters by `--source <name>` still work, and a future per-table view can
// add a sibling `_schema/tables/<table>/...` without churning this layer.

const sqlMigrationFileSizeLimit = 4 << 20 // 4 MB — migrations can be large

func cmdExtractSQLSchema(args []string) {
	o := defaultOpts()
	fs := flag.NewFlagSet("extract sql-schema", flag.ExitOnError)
	local := fs.String("local", "", "directory to scan for *.sql files (typically a Supabase migrations dir)")
	name := fs.String("name", "", "source name to write into (REQUIRED — extractor never invents one)")
	subdir := fs.String("subdir", "", "scan only this subpath under --local")
	var excludes stringSliceFlag
	fs.Var(&excludes, "exclude", "skip paths matching glob (repeatable; same semantics as pull --exclude)")
	bindOpts(fs, &o)
	fs.Parse(args)

	if *local == "" {
		die(fmt.Errorf("extract sql-schema: --local PATH is required"))
	}
	if *name == "" {
		die(fmt.Errorf("extract sql-schema: --name SOURCE is required (so extracted docs land under a known source)"))
	}
	abs, err := filepath.Abs(*local)
	if err != nil {
		die(err)
	}
	walkRoot := abs
	if *subdir != "" {
		walkRoot = filepath.Join(abs, *subdir)
	}
	if info, err := os.Stat(walkRoot); err != nil || !info.IsDir() {
		die(fmt.Errorf("extract sql-schema: %s is not a directory", walkRoot))
	}

	source := sanitizeSourceName(*name)
	if err := extractSQLSchemaInto(walkRoot, source, o, excludes, os.Args[1:], "_schema"); err != nil {
		die(err)
	}
}

// columnDef is a current-state record for one column. typeText holds the
// full type-and-modifier remainder of the column definition so the per-table
// doc can show "bigint generated by default as identity not null" without us
// having to re-parse it into structured fields.
//
// alterations records post-creation ALTER COLUMN events as human-readable
// strings (e.g. `20260201_x: SET NOT NULL`). We don't rewrite typeText
// because (a) the original CREATE TABLE shape is useful context for a
// reader, and (b) the structured rewrite would need a real PG type parser.
// Storing alter history as ordered strings is enough for FTS to match
// `column_name SET NOT NULL` and for the rendered doc to show evolution.
type columnDef struct {
	name        string
	typeText    string
	addedIn     string
	alterations []string
}

// migrationTouch is one (migration, table) intersection: the actions that
// migration applied to the table. Per-table docs aggregate these to show
// the chronological touch history.
type migrationTouch struct {
	base      string // basename without .sql, e.g. "20260101120000_init"
	timestamp string // 14-digit prefix if present, else ""
	actions   []string
	sourceURL string // file:// URL of the original .sql
}

type tablePolicyEntry struct {
	name      string
	migration string // base of the migration that introduced it
}

type tableIndexEntry struct {
	name      string
	migration string
}

type tableState struct {
	qualified  string
	migrations []migrationTouch
	policies   []tablePolicyEntry
	indexes    []tableIndexEntry
	columns    []columnDef // current state, updated by chronological replay
}

// collectTableStates walks .sql files in chronological order (by basename
// timestamp) and aggregates a per-table view: which migrations touched it,
// which policies/indexes were added, with provenance. Migrations without a
// numeric timestamp prefix sort last (lex order on basename), which matches
// Supabase convention and keeps "ad hoc" SQL files from masking the real
// migration history.
func collectTableStates(walkRoot string, excludes []string) (map[string]*tableState, error) {
	type fileEntry struct {
		path string // absolute
		rel  string // relative to walkRoot
		base string
		ts   string
	}
	var files []fileEntry

	walkErr := filepath.WalkDir(walkRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if p == walkRoot {
				return nil
			}
			if _, skip := skipDirs[d.Name()]; skip {
				return fs.SkipDir
			}
			if strings.HasPrefix(d.Name(), ".") {
				return fs.SkipDir
			}
			rel, _ := filepath.Rel(walkRoot, p)
			if excludeMatch(rel, excludes) {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".sql") {
			return nil
		}
		info, ierr := d.Info()
		if ierr != nil || info.Size() == 0 || info.Size() > sqlMigrationFileSizeLimit {
			return nil
		}
		rel, rerr := filepath.Rel(walkRoot, p)
		if rerr != nil {
			return rerr
		}
		if excludeMatch(rel, excludes) {
			return nil
		}
		base := strings.TrimSuffix(d.Name(), ".sql")
		files = append(files, fileEntry{path: p, rel: rel, base: base, ts: migrationTimestamp(d.Name())})
		return nil
	})
	if walkErr != nil {
		return nil, walkErr
	}

	// Stable chronological sort: timestamped migrations first (sorted by
	// timestamp), then non-timestamped files (e.g. ad-hoc fixes,
	// ROLLBACK_*) sorted by basename. This keeps the "Introduced in" line
	// pointing at the real first migration rather than at a rollback whose
	// empty-string timestamp would otherwise sort before "20251010...".
	sort.Slice(files, func(i, j int) bool {
		hasI, hasJ := files[i].ts != "", files[j].ts != ""
		if hasI != hasJ {
			return hasI // timestamped files come first
		}
		if hasI && files[i].ts != files[j].ts {
			return files[i].ts < files[j].ts
		}
		return files[i].base < files[j].base
	})

	states := map[string]*tableState{}
	getOrCreate := func(q string) *tableState {
		if s, ok := states[q]; ok {
			return s
		}
		s := &tableState{qualified: q}
		states[q] = s
		return s
	}

	for _, fe := range files {
		raw, err := os.ReadFile(fe.path)
		if err != nil {
			continue
		}
		tables, policies, indexes := scanSQLObjects(raw)
		sourceURL := "file://" + fe.path
		for _, t := range tables {
			st := getOrCreate(t.qualified)
			actionsCopy := append([]string(nil), t.actions...)
			st.migrations = append(st.migrations, migrationTouch{
				base:      fe.base,
				timestamp: fe.ts,
				actions:   actionsCopy,
				sourceURL: sourceURL,
			})
		}
		for _, p := range policies {
			st := getOrCreate(p.table)
			st.policies = append(st.policies, tablePolicyEntry{name: p.name, migration: fe.base})
		}
		for _, idx := range indexes {
			st := getOrCreate(idx.table)
			st.indexes = append(st.indexes, tableIndexEntry{name: idx.name, migration: fe.base})
		}
		// Column-aware replay: parse column definitions out of CREATE
		// TABLE blocks and apply ALTER COLUMN deltas in chronological
		// order. Comments must be stripped first so commented-out DDL
		// doesn't poison state.
		applyMigrationToTables(states, stripSQLComments(string(raw)), fe.base)
	}

	return states, nil
}

// renderTableMarkdown emits a per-table doc that's equally findable by table
// name (in title), policy name (in body), or index name (in body). The
// chronological migration list lets a reader follow the "how did this table
// get this way" trail without opening the SQL files individually.
//
// The first 200 bytes are intentionally keyword-dense ("table", "columns",
// "schema", the bare table name) so BM25 ranks this doc above migration
// docs that mention the table only in a "## Tables touched" list. Without
// this, queries like "users table columns" lost to migration docs whose
// term-frequency for "table" was higher despite lower relevance.
func renderTableMarkdown(t *tableState) []byte {
	var b strings.Builder
	bareName := t.qualified
	if i := strings.IndexByte(bareName, '.'); i >= 0 {
		bareName = bareName[i+1:]
	}
	// Repeat the bare name multiple times in the keyword-dense preamble.
	// BM25 with length-normalization punishes long docs; using a *generic*
	// "Table — columns" preamble caused short tables to outrank the right
	// match because they share the same generic phrase. Putting the bare
	// name (the actual selective term) twice in the first 100 bytes is
	// what lets `users table columns` rank `public.users` above
	// `template_categories`.
	fmt.Fprintf(&b, "# %s — schema for table %s\n\n", bareName, t.qualified)
	fmt.Fprintf(&b, "Columns, RLS policies, indexes, and migration history for the `%s` table (`%s`).\n\n", bareName, t.qualified)

	if len(t.migrations) > 0 {
		first := t.migrations[0]
		last := t.migrations[len(t.migrations)-1]
		fmt.Fprintf(&b, "Introduced in: `%s`\n\n", first.base)
		if last.base != first.base {
			fmt.Fprintf(&b, "Last touched in: `%s`\n\n", last.base)
		}
	}

	if len(t.columns) > 0 {
		fmt.Fprintf(&b, "## Columns (%d)\n\n", len(t.columns))
		for _, c := range t.columns {
			// "type" can be empty for malformed entries — emit just the
			// name so search still hits the column reference.
			if c.typeText == "" {
				fmt.Fprintf(&b, "- `%s` (added in `%s`)\n", c.name, c.addedIn)
			} else {
				fmt.Fprintf(&b, "- `%s` — %s (added in `%s`)\n", c.name, c.typeText, c.addedIn)
			}
			// Surface post-creation ALTER COLUMN events so a reader sees
			// `SET NOT NULL in 20260201_x` without having to grep migrations.
			for _, alt := range c.alterations {
				fmt.Fprintf(&b, "  - altered: `%s`\n", alt)
			}
		}
		b.WriteString("\n")
	}

	if len(t.migrations) > 0 {
		fmt.Fprintf(&b, "## Migrations (%d)\n\n", len(t.migrations))
		for _, m := range t.migrations {
			fmt.Fprintf(&b, "- `%s` — %s\n", m.base, strings.Join(m.actions, ", "))
		}
		b.WriteString("\n")
	}

	if len(t.policies) > 0 {
		fmt.Fprintf(&b, "## RLS policies (%d)\n\n", len(t.policies))
		for _, p := range t.policies {
			fmt.Fprintf(&b, "- `%s` (added in `%s`)\n", p.name, p.migration)
		}
		b.WriteString("\n")
	}

	if len(t.indexes) > 0 {
		fmt.Fprintf(&b, "## Indexes (%d)\n\n", len(t.indexes))
		for _, idx := range t.indexes {
			fmt.Fprintf(&b, "- `%s` (added in `%s`)\n", idx.name, idx.migration)
		}
		b.WriteString("\n")
	}

	return []byte(b.String())
}

// extractSQLSchemaInto is the testable core. It walks walkRoot for *.sql
// files, synthesizes per-migration markdown, and persists the results
// through the same write-lock + manifest + FTS update path as ingest().
// outPrefix is the per-source subtree name (default "_schema"); live
// extractors pass "_live" so their snapshots land in a sibling tree and
// don't collide with the per-migration history.
func extractSQLSchemaInto(walkRoot, source string, o pullOpts, excludes []string, cmdArgs []string, outPrefix string) error {
	if outPrefix == "" {
		outPrefix = "_schema"
	}
	start := time.Now()
	now := start.UTC().Format(time.RFC3339)
	srcOut := filepath.Join(o.out, source)
	if err := os.MkdirAll(srcOut, 0o755); err != nil {
		return err
	}

	type sqlDoc struct {
		rel     string // path within source dir, e.g. "_schema/migrations/<file>.md"
		url     string // origin URL (file:// of the source .sql)
		body    []byte
		sha     string
		fetched string
	}
	var docs []sqlDoc
	var walked, skipped, excluded int

	walkErr := filepath.WalkDir(walkRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if p == walkRoot {
				return nil
			}
			if _, skip := skipDirs[d.Name()]; skip {
				return fs.SkipDir
			}
			if strings.HasPrefix(d.Name(), ".") {
				return fs.SkipDir
			}
			rel, _ := filepath.Rel(walkRoot, p)
			if excludeMatch(rel, excludes) {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".sql") {
			return nil
		}
		walked++
		info, ierr := d.Info()
		if ierr != nil || info.Size() == 0 {
			skipped++
			return nil
		}
		if info.Size() > sqlMigrationFileSizeLimit {
			fmt.Fprintf(os.Stderr, "  SKIP %s — file > %d bytes\n", p, sqlMigrationFileSizeLimit)
			skipped++
			return nil
		}
		rel, rerr := filepath.Rel(walkRoot, p)
		if rerr != nil {
			return rerr
		}
		if excludeMatch(rel, excludes) {
			excluded++
			return nil
		}
		raw, rerr := os.ReadFile(p)
		if rerr != nil {
			skipped++
			return nil
		}
		md := renderSQLMigrationMarkdown(rel, raw)
		outRel := filepath.Join(outPrefix, "migrations", strings.TrimSuffix(rel, ".sql")+".md")
		sum := sha256.Sum256(md)
		docs = append(docs, sqlDoc{
			rel:     outRel,
			url:     "file://" + p,
			body:    md,
			sha:     hex.EncodeToString(sum[:]),
			fetched: now,
		})
		return nil
	})
	if walkErr != nil {
		return walkErr
	}

	// Per-table aggregation (cheap second walk — the migrations are small).
	// Done as a second pass so per-migration docs ship even if aggregation
	// has issues; failure here is logged but not fatal.
	tableStates, terr := collectTableStates(walkRoot, excludes)
	if terr != nil {
		fmt.Fprintf(os.Stderr, "extract sql-schema: per-table aggregation failed: %v (per-migration docs still written)\n", terr)
	} else {
		for q, st := range tableStates {
			body := renderTableMarkdown(st)
			outRel := filepath.Join(outPrefix, "tables", sanitizeTableFilename(q)+".md")
			sum := sha256.Sum256(body)
			// Synthetic URL: the file:// of the latest migration that
			// touched this table is what a reader would want to click,
			// but the manifest is URL-keyed and would collide with the
			// per-migration entry for the same .sql. extract-table:// is
			// distinct and includes the qualified name for traceability.
			docs = append(docs, sqlDoc{
				rel:     outRel,
				url:     "extract-table://" + source + "/" + q,
				body:    body,
				sha:     hex.EncodeToString(sum[:]),
				fetched: now,
			})
		}
	}

	// Stable order so manifest writes are deterministic across runs.
	sort.Slice(docs, func(i, j int) bool { return docs[i].rel < docs[j].rel })

	results := make([]result, 0, len(docs))
	for _, doc := range docs {
		results = append(results, result{
			URL:       doc.url,
			Source:    source,
			Path:      filepath.Join(source, doc.rel),
			Mode:      "extract:sql-schema",
			SHA256:    doc.sha,
			FetchedAt: doc.fetched,
		})
	}

	if err := withWriteLock(o.out, func() error {
		var changedPaths []string
		replaceOutputSubtree := outPrefix == "_live"
		if replaceOutputSubtree {
			replaceDir := filepath.Join(srcOut, outPrefix)
			if err := ensureSourcePathInsideOut(o.out, replaceDir); err != nil {
				return err
			}
			changedPaths = append(changedPaths, sourceMarkdownPaths(replaceDir, filepath.ToSlash(filepath.Join(source, outPrefix)))...)
			if err := os.RemoveAll(replaceDir); err != nil {
				return err
			}
		}
		for _, doc := range docs {
			outPath := filepath.Join(srcOut, doc.rel)
			if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(outPath, doc.body, 0o644); err != nil {
				return err
			}
		}
		for _, r := range results {
			changedPaths = append(changedPaths, r.Path)
		}
		if replaceOutputSubtree {
			mf, err := loadOrMigrateManifest(srcOut)
			if err != nil {
				return searchruntime.ManifestLoadSourceError(source, err)
			}
			pruneManifestPathPrefix(&mf, filepath.ToSlash(filepath.Join(source, outPrefix))+"/")
			mergeIntoManifest(&mf, results)
			if err := writeManifestAtomic(srcOut, mf); err != nil {
				return searchruntime.ManifestWriteSourceError(source, err)
			}
		} else if err := writeManifests(o.out, results, false, nil); err != nil {
			return err
		}
		if err := regenerateIndex(o.out, []string{source}); err != nil {
			return err
		}
		if idx, err := openFTSIndex(o.out); err == nil {
			if rerr := idx.updateFTS(o.out, uniqueStrings(changedPaths)); rerr != nil {
				fmt.Fprintf(os.Stderr, "fts5: update failed: %v\n", rerr)
			}
			idx.close()
		}
		entry := logEntry{
			StartedAt:  now,
			FinishedAt: time.Now().UTC().Format(time.RFC3339),
			ElapsedMs:  time.Since(start).Milliseconds(),
			Mode:       "extract:sql-schema",
			Args:       cmdArgs,
			Sources:    []string{source},
			URLs:       walked,
			Pulled:     len(results),
			Skipped:    skipped,
		}
		if err := appendIngestLog(o.out, entry); err != nil {
			fmt.Fprintf(os.Stderr, "ingest-log: append failed: %v\n", err)
		}
		return nil
	}); err != nil {
		return err
	}

	if excluded > 0 {
		fmt.Printf("extracted %d migrations into %s/%s/migrations/ (%d walked, %d skipped, %d excluded)\n",
			len(results), source, outPrefix, walked, skipped, excluded)
	} else {
		fmt.Printf("extracted %d migrations into %s/%s/migrations/ (%d walked, %d skipped)\n",
			len(results), source, outPrefix, walked, skipped)
	}
	return nil
}

func pruneManifestPathPrefix(m *manifest, prefix string) {
	if m == nil {
		return
	}
	for url, r := range m.Entries {
		if strings.HasPrefix(filepath.ToSlash(r.Path), prefix) {
			delete(m.Entries, url)
		}
	}
}

// renderSQLMigrationMarkdown wraps a migration's raw SQL in a doc that's
// search-friendly: heading uses the basename (so `--source x` + a query for
// the migration name lands here first), summary lists tables/policies the
// migration touches, and the original SQL is fenced verbatim.
func renderSQLMigrationMarkdown(relPath string, raw []byte) []byte {
	base := filepath.Base(relPath)
	title := strings.TrimSuffix(base, ".sql")

	tables, policies, indexes := scanSQLObjects(raw)

	var b strings.Builder
	fmt.Fprintf(&b, "# Migration: %s\n\n", title)
	fmt.Fprintf(&b, "Source path: `%s`\n\n", relPath)

	if ts := migrationTimestamp(base); ts != "" {
		fmt.Fprintf(&b, "Migration timestamp: `%s`\n\n", ts)
	}

	if len(tables) > 0 {
		b.WriteString("## Tables touched\n\n")
		for _, t := range tables {
			fmt.Fprintf(&b, "- %s — %s\n", t.qualified, strings.Join(t.actions, ", "))
		}
		b.WriteString("\n")
	}
	if len(policies) > 0 {
		b.WriteString("## RLS policies\n\n")
		for _, p := range policies {
			fmt.Fprintf(&b, "- `%s` on %s\n", p.name, p.table)
		}
		b.WriteString("\n")
	}
	if len(indexes) > 0 {
		b.WriteString("## Indexes\n\n")
		for _, i := range indexes {
			fmt.Fprintf(&b, "- `%s` on %s\n", i.name, i.table)
		}
		b.WriteString("\n")
	}

	b.WriteString("## SQL\n\n```sql\n")
	b.Write(raw)
	if len(raw) == 0 || raw[len(raw)-1] != '\n' {
		b.WriteString("\n")
	}
	b.WriteString("```\n")
	return []byte(b.String())
}

type sqlTableTouch struct {
	qualified string   // "public.users" or "users" if unqualified
	actions   []string // "CREATE", "ALTER", "DROP", "ENABLE RLS", ...
}

type sqlPolicyTouch struct {
	name  string
	table string
}

type sqlIndexTouch struct {
	name  string
	table string
}

// scanSQLObjects extracts a coarse inventory of what a migration touches.
// Regex-based on purpose — a real SQL parser would be overkill for surfacing
// table/policy/index names into the FTS index. False positives in comments
// are accepted (the SQL is still in the doc body either way).
func scanSQLObjects(raw []byte) ([]sqlTableTouch, []sqlPolicyTouch, []sqlIndexTouch) {
	src := string(raw)
	src = stripSQLComments(src)

	// Track per-action counts. We need counts (not just a set) to subtract
	// RLS-enable matches from raw ALTER matches: `alter table x enable
	// row level security` matches both reAlterTable and reEnableRLS, and
	// emitting "ALTER" for what is purely an RLS enable would be misleading.
	createN := map[string]int{}
	alterN := map[string]int{}
	dropN := map[string]int{}
	rlsN := map[string]int{}
	for _, m := range reCreateTable.FindAllStringSubmatch(src, -1) {
		createN[qualifyMatch(m)]++
	}
	for _, m := range reAlterTable.FindAllStringSubmatch(src, -1) {
		alterN[qualifyMatch(m)]++
	}
	for _, m := range reDropTable.FindAllStringSubmatch(src, -1) {
		dropN[qualifyMatch(m)]++
	}
	for _, m := range reEnableRLS.FindAllStringSubmatch(src, -1) {
		rlsN[qualifyMatch(m)]++
	}

	tableActions := map[string][]string{}
	addAction := func(q, action string) {
		q = strings.ToLower(q)
		for _, a := range tableActions[q] {
			if a == action {
				return
			}
		}
		tableActions[q] = append(tableActions[q], action)
	}
	for q := range createN {
		addAction(q, "CREATE")
	}
	for q, n := range alterN {
		// Strip RLS-enable matches; what remains are real ALTERs (column
		// adds, constraints, etc).
		if n-rlsN[q] > 0 {
			addAction(q, "ALTER")
		}
	}
	for q := range dropN {
		addAction(q, "DROP")
	}
	for q := range rlsN {
		addAction(q, "ENABLE RLS")
	}

	tables := make([]sqlTableTouch, 0, len(tableActions))
	for q, actions := range tableActions {
		tables = append(tables, sqlTableTouch{qualified: q, actions: actions})
	}
	sort.Slice(tables, func(i, j int) bool { return tables[i].qualified < tables[j].qualified })

	var policies []sqlPolicyTouch
	for _, m := range reCreatePolicy.FindAllStringSubmatch(src, -1) {
		// Groups: [1]=policy name, [2..5]=schema-quoted, schema-unquoted,
		// table-quoted, table-unquoted (paired identifiers).
		policies = append(policies, sqlPolicyTouch{
			name:  m[1],
			table: qualify(pickGroup(m, 2, 3), pickGroup(m, 4, 5)),
		})
	}
	sort.Slice(policies, func(i, j int) bool {
		if policies[i].table != policies[j].table {
			return policies[i].table < policies[j].table
		}
		return policies[i].name < policies[j].name
	})

	var indexes []sqlIndexTouch
	for _, m := range reCreateIndex.FindAllStringSubmatch(src, -1) {
		// Groups: [1]=name-quoted, [2]=name-unquoted, [3..6]=schema/table
		// paired identifiers.
		indexes = append(indexes, sqlIndexTouch{
			name:  pickGroup(m, 1, 2),
			table: qualify(pickGroup(m, 3, 4), pickGroup(m, 5, 6)),
		})
	}
	sort.Slice(indexes, func(i, j int) bool {
		if indexes[i].table != indexes[j].table {
			return indexes[i].table < indexes[j].table
		}
		return indexes[i].name < indexes[j].name
	})

	return tables, policies, indexes
}

// sanitizeTableFilename strips characters that are awkward in filenames or
// URLs from a qualified name. We keep dots so the schema.table convention
// stays readable in the index.
func sanitizeTableFilename(q string) string {
	var b strings.Builder
	for _, r := range q {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '.' || r == '_' || r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		out = "unnamed"
	}
	return out
}

// latestMigrationURL returns the file:// URL of the chronologically last
// migration that touched the table. Empty string if the table has no
// migration touches recorded (only policies/indexes).
func latestMigrationURL(t *tableState) string {
	if len(t.migrations) == 0 {
		return ""
	}
	return t.migrations[len(t.migrations)-1].sourceURL
}

// qualify joins schema + table into "schema.table". Bare table names get
// the "public." prefix because Supabase/PG default the search path to
// public. Without this, the same table referenced once as "public.users"
// and once as plain "users" would split into two state buckets and the
// per-table doc would lose half its history.
func qualify(schema, table string) string {
	schema = strings.Trim(strings.ToLower(schema), `"`)
	table = strings.Trim(strings.ToLower(table), `"`)
	if schema == "" {
		schema = "public"
	}
	return schema + "." + table
}

// pickGroup returns the first non-empty group at the given indices. Used to
// flatten the (?:"x"|x) alternation pattern into a single resolved value.
// Out-of-bounds indices are tolerated (returns "" rather than panicking) so
// callers that only sometimes have all groups populated stay simple.
func pickGroup(m []string, idxs ...int) string {
	for _, i := range idxs {
		if i < len(m) && m[i] != "" {
			return m[i]
		}
	}
	return ""
}

// qualifyMatch handles the common case of a single paired identifier
// (optional schema followed by a required table name) where the regex
// produces 4 capture groups: [1,2]=schema, [3,4]=table.
func qualifyMatch(m []string) string {
	return qualify(pickGroup(m, 1, 2), pickGroup(m, 3, 4))
}

var (
	// Each regex tolerates: optional double-quoted identifiers, optional
	// schema qualifier, optional IF [NOT] EXISTS, leading whitespace.
	// Identifier captures: [1]=schema (may be empty), [2]=table.
	identifier = `(?:"([A-Za-z_][\w]*)"|([A-Za-z_][\w]*))`

	// `CREATE TABLE [IF NOT EXISTS] [schema.]table`
	reCreateTable = regexp.MustCompile(`(?im)^\s*create\s+table\s+(?:if\s+not\s+exists\s+)?(?:` + identifier + `\.)?` + identifier)

	// `ALTER TABLE [ONLY] [schema.]table`
	reAlterTable = regexp.MustCompile(`(?im)^\s*alter\s+table\s+(?:only\s+)?(?:` + identifier + `\.)?` + identifier)

	// `DROP TABLE [IF EXISTS] [schema.]table`
	reDropTable = regexp.MustCompile(`(?im)^\s*drop\s+table\s+(?:if\s+exists\s+)?(?:` + identifier + `\.)?` + identifier)

	// `ALTER TABLE [schema.]table ENABLE ROW LEVEL SECURITY`
	reEnableRLS = regexp.MustCompile(`(?im)^\s*alter\s+table\s+(?:` + identifier + `\.)?` + identifier + `\s+enable\s+row\s+level\s+security`)

	// `CREATE POLICY "name" ON [schema.]table`. Quoted name is required by
	// PG's grammar in practice (Supabase always quotes).
	reCreatePolicy = regexp.MustCompile(`(?im)^\s*create\s+policy\s+"([^"]+)"\s+on\s+(?:` + identifier + `\.)?` + identifier)

	// `CREATE [UNIQUE] INDEX [IF NOT EXISTS] name ON [schema.]table`
	reCreateIndex = regexp.MustCompile(`(?im)^\s*create\s+(?:unique\s+)?index\s+(?:if\s+not\s+exists\s+)?(?:"([^"]+)"|([A-Za-z_][\w]*))\s+on\s+(?:` + identifier + `\.)?` + identifier)
)

// reMigrationTS captures the leading numeric timestamp of a Supabase
// migration filename like 20251013180000_fix_foo.sql.
var reMigrationTS = regexp.MustCompile(`^(\d{14})_`)

func migrationTimestamp(base string) string {
	if m := reMigrationTS.FindStringSubmatch(base); m != nil {
		return m[1]
	}
	return ""
}

// stripSQLComments removes "-- line comments" and /* block comments */ so
// regex matches don't trip on commented-out DDL. It's fine to be conservative
// — extractor output is a search aid, not authoritative schema state.
func stripSQLComments(src string) string {
	var b strings.Builder
	i := 0
	for i < len(src) {
		if i+1 < len(src) && src[i] == '-' && src[i+1] == '-' {
			j := strings.IndexByte(src[i:], '\n')
			if j < 0 {
				break
			}
			i += j
			continue
		}
		if i+1 < len(src) && src[i] == '/' && src[i+1] == '*' {
			j := strings.Index(src[i+2:], "*/")
			if j < 0 {
				break
			}
			i += j + 4
			continue
		}
		b.WriteByte(src[i])
		i++
	}
	return b.String()
}

// findCreateTableBlock finds the column-list inside a `CREATE TABLE` block
// at or after `from`, returning (qualified-name, inner-text, end-index, ok).
// Inner text is the substring between the matching parens; end-index points
// after the closing paren so the caller can keep scanning.
//
// Paren-balanced read is mandatory because column types and CHECK
// constraints can include their own parens (e.g. `numeric(10,2)`,
// `check (status in ('a','b'))`).
func findCreateTableBlock(src string, from int) (qualified, inner string, end int, ok bool) {
	loc := reCreateTable.FindStringSubmatchIndex(src[from:])
	if loc == nil {
		return "", "", 0, false
	}
	// loc[0] = start of full match; submatches are offset.
	// We need the table-qualified-name from the regex submatches and the
	// position of the next '(' after the match.
	start := from + loc[0]
	headerEnd := from + loc[1]
	// Extract qualified name from submatches. reCreateTable matches the
	// schema-paired and table-paired identifiers in groups [1,2,3,4].
	groups := reCreateTable.FindStringSubmatch(src[from:])
	if len(groups) < 5 {
		return "", "", 0, false
	}
	q := qualify(pickGroup(groups, 1, 2), pickGroup(groups, 3, 4))

	// Skip whitespace until we find '(' (CREATE TABLE allows table options
	// like INHERITS or column-list to be separated by whitespace; in
	// practice Supabase uses `create table x (`).
	i := headerEnd
	for i < len(src) && (src[i] == ' ' || src[i] == '\t' || src[i] == '\n') {
		i++
	}
	if i >= len(src) || src[i] != '(' {
		// No column list — likely "create table x as select ...". Skip;
		// callers won't get column data for this table from this block.
		return q, "", start + len("create table"), true
	}
	// Read paren-balanced. respect single-quoted strings (PG uses '..' for
	// strings, '' is the escape so a doubled '' should be treated as a
	// literal quote inside the string state) and double-quoted identifiers.
	depth := 1
	i++ // past opening '('
	startInner := i
	inSingle, inDouble := false, false
	for i < len(src) {
		c := src[i]
		switch {
		case inSingle:
			if c == '\'' {
				if i+1 < len(src) && src[i+1] == '\'' {
					i++ // doubled '' is escaped quote
				} else {
					inSingle = false
				}
			}
		case inDouble:
			if c == '"' {
				inDouble = false
			}
		case c == '\'':
			inSingle = true
		case c == '"':
			inDouble = true
		case c == '(':
			depth++
		case c == ')':
			depth--
			if depth == 0 {
				return q, src[startInner:i], i + 1, true
			}
		}
		i++
	}
	// Unterminated CREATE TABLE — give up gracefully.
	return q, "", start, false
}

// splitColumnList breaks a CREATE TABLE column-list text into entries on
// top-level commas (commas inside parens or quoted strings are preserved).
// Same string-state tracking as findCreateTableBlock.
func splitColumnList(s string) []string {
	var out []string
	var cur strings.Builder
	depth := 0
	inSingle, inDouble := false, false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case inSingle:
			cur.WriteByte(c)
			if c == '\'' {
				if i+1 < len(s) && s[i+1] == '\'' {
					cur.WriteByte(s[i+1])
					i++
				} else {
					inSingle = false
				}
			}
		case inDouble:
			cur.WriteByte(c)
			if c == '"' {
				inDouble = false
			}
		case c == '\'':
			inSingle = true
			cur.WriteByte(c)
		case c == '"':
			inDouble = true
			cur.WriteByte(c)
		case c == '(':
			depth++
			cur.WriteByte(c)
		case c == ')':
			depth--
			cur.WriteByte(c)
		case c == ',' && depth == 0:
			out = append(out, strings.TrimSpace(cur.String()))
			cur.Reset()
		default:
			cur.WriteByte(c)
		}
	}
	if cur.Len() > 0 {
		if s := strings.TrimSpace(cur.String()); s != "" {
			out = append(out, s)
		}
	}
	return out
}

// constraintPrefixes are first-word patterns that mean a column-list entry
// is actually a table-level constraint, not a column. Order matters only
// in that "constraint <name> primary key (...)" starts with `constraint`
// and is caught by the bare prefix.
var constraintPrefixes = []string{
	"primary key", "foreign key", "unique", "check",
	"constraint", "exclude", "like",
}

// parseColumnEntry takes a single column-list chunk and decides whether
// it's a real column (returns name + remaining type-text) or a table-level
// constraint (returns ok=false). The first identifier is the column name;
// the rest is type + modifiers verbatim.
func parseColumnEntry(entry string) (name, typeText string, ok bool) {
	low := strings.ToLower(strings.TrimSpace(entry))
	for _, p := range constraintPrefixes {
		if strings.HasPrefix(low, p+" ") || strings.HasPrefix(low, p+"(") {
			return "", "", false
		}
	}
	// Identifier: either "quoted" or bareword. Strip leading whitespace,
	// then read the identifier and the remainder.
	s := strings.TrimSpace(entry)
	if s == "" {
		return "", "", false
	}
	if s[0] == '"' {
		end := strings.IndexByte(s[1:], '"')
		if end < 0 {
			return "", "", false
		}
		name = s[1 : 1+end]
		rest := strings.TrimSpace(s[1+end+1:])
		return strings.ToLower(name), rest, true
	}
	// Bareword: read [A-Za-z_][\w]*.
	i := 0
	for i < len(s) && (isIdentByte(s[i])) {
		i++
	}
	if i == 0 {
		return "", "", false
	}
	name = s[:i]
	rest := strings.TrimSpace(s[i:])
	return strings.ToLower(name), rest, true
}

func isIdentByte(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

// reAlterAddColumn captures `ALTER TABLE x ADD COLUMN [IF NOT EXISTS] name`.
// The trailing type-text is consumed by the caller from the source string
// because it can include arbitrary expressions (defaults, check constraints)
// that don't fit cleanly in a regex group.
var reAlterAddColumn = regexp.MustCompile(`(?im)\badd\s+column\s+(?:if\s+not\s+exists\s+)?(?:"([^"]+)"|([A-Za-z_][\w]*))\s+`)

// reAlterDropColumn captures the dropped column name.
var reAlterDropColumn = regexp.MustCompile(`(?im)\bdrop\s+column\s+(?:if\s+exists\s+)?(?:"([^"]+)"|([A-Za-z_][\w]*))`)

// reAlterRenameColumn captures (old, new).
var reAlterRenameColumn = regexp.MustCompile(`(?im)\brename\s+column\s+(?:"([^"]+)"|([A-Za-z_][\w]*))\s+to\s+(?:"([^"]+)"|([A-Za-z_][\w]*))`)

// ALTER TABLE x ALTER COLUMN c <action> patterns. We capture the column
// name only and read the action keyword(s) from the surrounding match —
// each variant has its own regex so the readable rendering stays simple.
//
// Note on `alter column type type "public"."earnings_type"`: when a column
// is named `type`, real-world PG migrations write `alter column "type" type
// <new_type>` or `alter column type type ...`. The regex matches the column
// name as the first identifier and consumes the keyword `type` separately.
var (
	reAlterColumnType        = regexp.MustCompile(`(?im)\balter\s+column\s+(?:"([^"]+)"|([A-Za-z_][\w]*))\s+(?:set\s+data\s+)?type\s+`)
	reAlterColumnSetNotNull  = regexp.MustCompile(`(?im)\balter\s+column\s+(?:"([^"]+)"|([A-Za-z_][\w]*))\s+set\s+not\s+null`)
	reAlterColumnDropNotNull = regexp.MustCompile(`(?im)\balter\s+column\s+(?:"([^"]+)"|([A-Za-z_][\w]*))\s+drop\s+not\s+null`)
	reAlterColumnSetDefault  = regexp.MustCompile(`(?im)\balter\s+column\s+(?:"([^"]+)"|([A-Za-z_][\w]*))\s+set\s+default\b`)
	reAlterColumnDropDefault = regexp.MustCompile(`(?im)\balter\s+column\s+(?:"([^"]+)"|([A-Za-z_][\w]*))\s+drop\s+default`)
)

// reAlterTableHeader is the full `ALTER TABLE [ONLY] [schema.]table` prefix.
// Used to split a multi-clause ALTER (one ALTER TABLE with several `add
// column ...` clauses) into per-table ranges so we know which table each
// add/drop applies to.
var reAlterTableHeader = regexp.MustCompile(`(?im)^\s*alter\s+table\s+(?:only\s+)?(?:` + identifier + `\.)?` + identifier)

// applyMigrationToTables mutates `states` to reflect what `src` (one
// migration's full SQL, with comments stripped) does to columns. It walks
// CREATE TABLE blocks and ALTER TABLE statements in source order and
// records column adds/drops/renames. Each new column carries `migration`
// as its provenance.
func applyMigrationToTables(states map[string]*tableState, src, migration string) {
	getOrCreate := func(q string) *tableState {
		if s, ok := states[q]; ok {
			return s
		}
		s := &tableState{qualified: q}
		states[q] = s
		return s
	}

	// 1. CREATE TABLE blocks: each one (re)defines the column set.
	pos := 0
	for pos < len(src) {
		q, inner, next, ok := findCreateTableBlock(src, pos)
		if !ok {
			break
		}
		if q != "" && inner != "" {
			st := getOrCreate(q)
			// Replace columns wholesale — a CREATE TABLE redefines the
			// table. (CREATE IF NOT EXISTS still parses the column list,
			// which mostly matches what's already there in practice.)
			var cols []columnDef
			for _, entry := range splitColumnList(inner) {
				name, typeText, isCol := parseColumnEntry(entry)
				if !isCol {
					continue
				}
				cols = append(cols, columnDef{name: name, typeText: typeText, addedIn: migration})
			}
			st.columns = cols
		}
		pos = next
	}

	// 2. ALTER TABLE statements. Find each `alter table x ...` header,
	// then within its scope (until the next ALTER TABLE or end of file)
	// apply the add/drop/rename clauses.
	headers := reAlterTableHeader.FindAllStringSubmatchIndex(src, -1)
	for i, h := range headers {
		// h[0]:h[1] is the matched header; submatch indices follow.
		hStart := h[0]
		hEnd := h[1]
		var scopeEnd int
		if i+1 < len(headers) {
			scopeEnd = headers[i+1][0]
		} else {
			scopeEnd = len(src)
		}
		// Pull qualified name from header submatches.
		groups := reAlterTableHeader.FindStringSubmatch(src[hStart:hEnd])
		if len(groups) < 5 {
			continue
		}
		q := qualify(pickGroup(groups, 1, 2), pickGroup(groups, 3, 4))
		st := getOrCreate(q)
		body := src[hEnd:scopeEnd]

		// Add column: capture name + read forward to find the column's
		// type text (everything until the next clause or terminating ;).
		// Capture-group indices are -1 when that branch of the alternation
		// didn't match, so we have to test before slicing.
		for _, m := range reAlterAddColumn.FindAllStringSubmatchIndex(body, -1) {
			var name string
			if m[2] >= 0 && m[3] >= 0 {
				name = body[m[2]:m[3]]
			} else if m[4] >= 0 && m[5] >= 0 {
				name = body[m[4]:m[5]]
			}
			name = strings.ToLower(strings.Trim(name, `"`))
			// Type text = from end of regex match up to next top-level
			// comma or ; — whichever comes first. Use the same paren+
			// quote tracking as splitColumnList.
			typeText := readUntilClauseEnd(body[m[1]:])
			// Replace if column already exists (idempotent IF NOT EXISTS),
			// otherwise append.
			st.columns = upsertColumn(st.columns, columnDef{
				name:     name,
				typeText: typeText,
				addedIn:  migration,
			})
		}
		for _, m := range reAlterDropColumn.FindAllStringSubmatch(body, -1) {
			name := pickGroup(m, 1, 2)
			name = strings.ToLower(strings.Trim(name, `"`))
			st.columns = dropColumn(st.columns, name)
		}
		for _, m := range reAlterRenameColumn.FindAllStringSubmatch(body, -1) {
			oldN := strings.ToLower(strings.Trim(pickGroup(m, 1, 2), `"`))
			newN := strings.ToLower(strings.Trim(pickGroup(m, 3, 4), `"`))
			st.columns = renameColumn(st.columns, oldN, newN)
		}
		// ALTER COLUMN type/null/default — record as alterations on the
		// existing columnDef without rewriting typeText. Each event is
		// idempotent within a migration (regex matches all instances; we
		// don't dedup against a prior event in the same file).
		recordAlter := func(re *regexp.Regexp, action string) {
			for _, m := range re.FindAllStringSubmatch(body, -1) {
				name := strings.ToLower(strings.Trim(pickGroup(m, 1, 2), `"`))
				st.columns = annotateColumn(st.columns, name, migration+": "+action)
			}
		}
		recordAlter(reAlterColumnType, "TYPE change")
		recordAlter(reAlterColumnSetNotNull, "SET NOT NULL")
		recordAlter(reAlterColumnDropNotNull, "DROP NOT NULL")
		recordAlter(reAlterColumnSetDefault, "SET DEFAULT")
		recordAlter(reAlterColumnDropDefault, "DROP DEFAULT")
	}
}

func annotateColumn(cols []columnDef, name, note string) []columnDef {
	for i, e := range cols {
		if e.name == name {
			cols[i].alterations = append(cols[i].alterations, note)
			return cols
		}
	}
	return cols
}

// readUntilClauseEnd reads from the start of a column-type expression up to
// the next top-level comma or semicolon. Used to pull the full
// "type modifiers default expr" remainder for ALTER ... ADD COLUMN.
func readUntilClauseEnd(s string) string {
	depth := 0
	inSingle, inDouble := false, false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case inSingle:
			if c == '\'' {
				if i+1 < len(s) && s[i+1] == '\'' {
					i++
				} else {
					inSingle = false
				}
			}
		case inDouble:
			if c == '"' {
				inDouble = false
			}
		case c == '\'':
			inSingle = true
		case c == '"':
			inDouble = true
		case c == '(':
			depth++
		case c == ')':
			depth--
		case (c == ',' || c == ';') && depth == 0:
			return strings.TrimSpace(s[:i])
		}
	}
	return strings.TrimSpace(s)
}

func upsertColumn(cols []columnDef, c columnDef) []columnDef {
	for i, e := range cols {
		if e.name == c.name {
			cols[i].typeText = c.typeText
			return cols
		}
	}
	return append(cols, c)
}

func dropColumn(cols []columnDef, name string) []columnDef {
	for i, e := range cols {
		if e.name == name {
			return append(cols[:i], cols[i+1:]...)
		}
	}
	return cols
}

func renameColumn(cols []columnDef, oldN, newN string) []columnDef {
	for i, e := range cols {
		if e.name == oldN {
			cols[i].name = newN
			return cols
		}
	}
	return cols
}
