// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ftsdb

type Doc struct {
	Rowid      int64
	Path       string
	Source     string
	Title      *string
	PathTokens string
	Body       string
	Url        *string
	IsHub      int64
}

type DocsPath struct {
	Path  string
	Rowid int64
}
