// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package ftsdb

import (
	"context"
	"database/sql"
)

const countDocs = `-- name: CountDocs :one
SELECT CAST(COUNT(*) AS INTEGER) FROM docs
`

func (q *Queries) CountDocs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAllDocs = `-- name: DeleteAllDocs :exec
DELETE FROM docs
`

func (q *Queries) DeleteAllDocs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDocs)
	return err
}

const deleteAllDocsPath = `-- name: DeleteAllDocsPath :exec
DELETE FROM docs_path
`

func (q *Queries) DeleteAllDocsPath(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDocsPath)
	return err
}

const deleteDocByRowID = `-- name: DeleteDocByRowID :exec
DELETE FROM docs WHERE rowid = ?
`

func (q *Queries) DeleteDocByRowID(ctx context.Context, rowid int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocByRowID, rowid)
	return err
}

const deleteDocsBySource = `-- name: DeleteDocsBySource :exec
DELETE FROM docs WHERE source = ?
`

func (q *Queries) DeleteDocsBySource(ctx context.Context, source string) error {
	_, err := q.db.ExecContext(ctx, deleteDocsBySource, source)
	return err
}

const deletePathByPath = `-- name: DeletePathByPath :exec
DELETE FROM docs_path WHERE path = ?
`

func (q *Queries) DeletePathByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deletePathByPath, path)
	return err
}

const deletePathsBySource = `-- name: DeletePathsBySource :exec
DELETE FROM docs_path
WHERE "rowid" IN (SELECT "rowid" FROM docs WHERE source = ?)
`

func (q *Queries) DeletePathsBySource(ctx context.Context, source string) error {
	_, err := q.db.ExecContext(ctx, deletePathsBySource, source)
	return err
}

const dropDocs = `-- name: DropDocs :exec
DROP TABLE IF EXISTS docs
`

func (q *Queries) DropDocs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropDocs)
	return err
}

const dropDocsPath = `-- name: DropDocsPath :exec
DROP TABLE IF EXISTS docs_path
`

func (q *Queries) DropDocsPath(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropDocsPath)
	return err
}

const insertDoc = `-- name: InsertDoc :execresult
INSERT INTO docs(path, source, title, path_tokens, body, url, is_hub)
VALUES(?, ?, ?, ?, ?, ?, ?)
`

type InsertDocParams struct {
	Path       string
	Source     string
	Title      *string
	PathTokens string
	Body       string
	Url        *string
	IsHub      int64
}

func (q *Queries) InsertDoc(ctx context.Context, arg InsertDocParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertDoc,
		arg.Path,
		arg.Source,
		arg.Title,
		arg.PathTokens,
		arg.Body,
		arg.Url,
		arg.IsHub,
	)
}

const insertDocWithRowID = `-- name: InsertDocWithRowID :exec
INSERT INTO docs("rowid", path, source, title, path_tokens, body, url, is_hub)
VALUES(?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDocWithRowIDParams struct {
	Rowid      int64
	Path       string
	Source     string
	Title      *string
	PathTokens string
	Body       string
	Url        *string
	IsHub      int64
}

func (q *Queries) InsertDocWithRowID(ctx context.Context, arg InsertDocWithRowIDParams) error {
	_, err := q.db.ExecContext(ctx, insertDocWithRowID,
		arg.Rowid,
		arg.Path,
		arg.Source,
		arg.Title,
		arg.PathTokens,
		arg.Body,
		arg.Url,
		arg.IsHub,
	)
	return err
}

const insertPath = `-- name: InsertPath :exec
INSERT INTO docs_path(path, "rowid") VALUES(?, ?)
`

type InsertPathParams struct {
	Path  string
	Rowid int64
}

func (q *Queries) InsertPath(ctx context.Context, arg InsertPathParams) error {
	_, err := q.db.ExecContext(ctx, insertPath, arg.Path, arg.Rowid)
	return err
}

const lookupDocRowIDByPath = `-- name: LookupDocRowIDByPath :one
SELECT CAST("rowid" AS INTEGER) FROM docs_path WHERE path = ?
`

func (q *Queries) LookupDocRowIDByPath(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, lookupDocRowIDByPath, path)
	var rowid int64
	err := row.Scan(&rowid)
	return rowid, err
}

const probeDocsIsHub = `-- name: ProbeDocsIsHub :many

SELECT is_hub FROM docs LIMIT 0
`

// Static FTS cache queries for docs-puller. Dynamic ranking SELECTs stay in Go
// because they compose tier-specific projections and optional source filters.
func (q *Queries) ProbeDocsIsHub(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, probeDocsIsHub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var is_hub int64
		if err := rows.Scan(&is_hub); err != nil {
			return nil, err
		}
		items = append(items, is_hub)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildPaths = `-- name: RebuildPaths :exec
INSERT INTO docs_path(path, "rowid") SELECT path, "rowid" FROM docs
`

func (q *Queries) RebuildPaths(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rebuildPaths)
	return err
}
