/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Worker liveness without calling the origin. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check the token-gated origin and corpus. */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the public engine, build, corpus, and limit identity. */
        get: operations["getDemoMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the closed set of reviewed public sources. */
        get: operations["listDemoSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the public sample with SQLite FTS5. */
        get: operations["searchDemo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/doc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one bounded reviewed document as plain Markdown. */
        get: operations["getDemoDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SourceID: "sqlite" | "go" | "postgresql";
        /** @example sha256:0000000000000000000000000000000000000000000000000000000000000000 */
        Digest: string;
        HealthResponse: {
            /** @constant */
            ok: true;
            /** @constant */
            service: "docs-puller-demo";
            build_id: string;
        };
        ReadinessResponse: {
            /** @constant */
            ok: true;
            /** @constant */
            service: "docs-puller-demo";
            /** @constant */
            origin: "ready";
            corpus: components["schemas"]["CorpusIdentity"];
            /** Format: date-time */
            checked_at: string;
        };
        EngineIdentity: {
            /** @constant */
            name: "docs-puller";
            version: string;
            /** @constant */
            mode: "fts5";
        };
        CorpusIdentity: {
            /** @constant */
            id: "public-sample-v1";
            digest: components["schemas"]["Digest"];
            index_digest: components["schemas"]["Digest"];
            /** @constant */
            document_count: 24;
            /** @constant */
            source_count: 3;
            /** Format: date-time */
            retrieved_at: string;
        };
        MetaResponse: {
            /** @constant */
            ok: true;
            /** @constant */
            schema_version: 1;
            /** @constant */
            service: "docs-puller-demo";
            engine: components["schemas"]["EngineIdentity"];
            build_id: string;
            commit: string;
            /** Format: date-time */
            deployed_at: string;
            corpus: components["schemas"]["CorpusIdentity"];
            limits: {
                /** @constant */
                query_characters: 160;
                /** @constant */
                results: 10;
                /** @constant */
                timeout_ms: 4000;
                /** @constant */
                response_bytes: 65536;
            };
        };
        Source: {
            id: components["schemas"]["SourceID"];
            label: string;
            document_count: number;
            /** Format: uri */
            homepage: string;
            license: string;
        };
        SourcesResponse: {
            /** @constant */
            ok: true;
            corpus: components["schemas"]["CorpusIdentity"];
            sources: components["schemas"]["Source"][];
        };
        Snippet: {
            line: number;
            text: string;
        };
        SearchResult: {
            title: string;
            source: components["schemas"]["SourceID"];
            path: string;
            /** Format: uri */
            url: string;
            score: number;
            snippets: components["schemas"]["Snippet"][];
        };
        SearchResponse: {
            /** @constant */
            ok: true;
            query: string;
            /** @constant */
            engine: "docs-puller";
            /** @constant */
            mode: "fts5";
            elapsed_ms: number;
            result_count: number;
            corpus: components["schemas"]["CorpusIdentity"];
            results: components["schemas"]["SearchResult"][];
        };
        DocumentResponse: {
            /** @constant */
            ok: true;
            source: components["schemas"]["SourceID"];
            path: string;
            title: string;
            /** Format: uri */
            url: string;
            /** @constant */
            content_type: "text/markdown";
            content: string;
            bytes: number;
            corpus: components["schemas"]["CorpusIdentity"];
        };
        ErrorResponse: {
            /** @constant */
            ok: false;
            error: {
                /** @enum {string} */
                code: "invalid_request" | "not_found" | "rate_limited" | "origin_invalid" | "origin_unavailable" | "origin_timeout" | "internal_error";
                message: string;
                request_id: string;
                retry_after_seconds?: number;
            };
        };
    };
    responses: {
        /** @description The request did not match the closed public contract. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The reviewed document does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The bounded public request budget was exceeded. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The origin returned an invalid public response. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The public demo is temporarily unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The origin did not answer within four seconds. */
        GatewayTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Worker is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Worker and origin are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDemoMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public demo metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listDemoSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviewed source list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    searchDemo: {
        parameters: {
            query: {
                /** @description A normalized Unicode query. Raw queries are not written to telemetry. */
                q: string;
                source?: components["schemas"]["SourceID"];
                limit?: number;
                mode?: "fts5";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded FTS5 results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    getDemoDocument: {
        parameters: {
            query: {
                source: components["schemas"]["SourceID"];
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A reviewed Markdown document. Clients must render it as text. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
}
