// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embed_query.sql

package embeddb

import (
	"context"
)

const inspectEmbeddingCacheByModel = `-- name: InspectEmbeddingCacheByModel :one
SELECT CAST(COUNT(*) AS INTEGER) AS count,
       CAST(COALESCE(MAX(dim), 0) AS INTEGER) AS dim
FROM embeddings
WHERE model = ?
`

type InspectEmbeddingCacheByModelRow struct {
	Count int64
	Dim   int64
}

func (q *Queries) InspectEmbeddingCacheByModel(ctx context.Context, model string) (InspectEmbeddingCacheByModelRow, error) {
	row := q.db.QueryRowContext(ctx, inspectEmbeddingCacheByModel, model)
	var i InspectEmbeddingCacheByModelRow
	err := row.Scan(&i.Count, &i.Dim)
	return i, err
}

const listAllEmbeddingChunks = `-- name: ListAllEmbeddingChunks :many
SELECT path, chunk_idx, chunk_size, mtime_ns, model, dim, vec
FROM embedding_chunks
`

func (q *Queries) ListAllEmbeddingChunks(ctx context.Context) ([]EmbeddingChunk, error) {
	rows, err := q.db.QueryContext(ctx, listAllEmbeddingChunks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddingChunk{}
	for rows.Next() {
		var i EmbeddingChunk
		if err := rows.Scan(
			&i.Path,
			&i.ChunkIdx,
			&i.ChunkSize,
			&i.MtimeNs,
			&i.Model,
			&i.Dim,
			&i.Vec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEmbeddings = `-- name: ListAllEmbeddings :many

SELECT path, mtime_ns, model, dim, vec
FROM embeddings
`

// Static embedding-store queries. Dynamic vector candidate queries that need
// runtime IN-list expansion stay in embed.go.
func (q *Queries) ListAllEmbeddings(ctx context.Context) ([]Embedding, error) {
	rows, err := q.db.QueryContext(ctx, listAllEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Embedding{}
	for rows.Next() {
		var i Embedding
		if err := rows.Scan(
			&i.Path,
			&i.MtimeNs,
			&i.Model,
			&i.Dim,
			&i.Vec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingChunkMtimesByModelAndChunkSize = `-- name: ListEmbeddingChunkMtimesByModelAndChunkSize :many
SELECT path, chunk_idx, mtime_ns
FROM embedding_chunks
WHERE model = ? AND chunk_size = ?
`

type ListEmbeddingChunkMtimesByModelAndChunkSizeParams struct {
	Model     string
	ChunkSize int64
}

type ListEmbeddingChunkMtimesByModelAndChunkSizeRow struct {
	Path     string
	ChunkIdx int64
	MtimeNs  int64
}

func (q *Queries) ListEmbeddingChunkMtimesByModelAndChunkSize(ctx context.Context, arg ListEmbeddingChunkMtimesByModelAndChunkSizeParams) ([]ListEmbeddingChunkMtimesByModelAndChunkSizeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingChunkMtimesByModelAndChunkSize, arg.Model, arg.ChunkSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingChunkMtimesByModelAndChunkSizeRow{}
	for rows.Next() {
		var i ListEmbeddingChunkMtimesByModelAndChunkSizeRow
		if err := rows.Scan(&i.Path, &i.ChunkIdx, &i.MtimeNs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingFlatRowsByModel = `-- name: ListEmbeddingFlatRowsByModel :many
SELECT path, dim, vec
FROM embeddings
WHERE model = ?
ORDER BY path
`

type ListEmbeddingFlatRowsByModelRow struct {
	Path string
	Dim  int64
	Vec  []byte
}

func (q *Queries) ListEmbeddingFlatRowsByModel(ctx context.Context, model string) ([]ListEmbeddingFlatRowsByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingFlatRowsByModel, model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingFlatRowsByModelRow{}
	for rows.Next() {
		var i ListEmbeddingFlatRowsByModelRow
		if err := rows.Scan(&i.Path, &i.Dim, &i.Vec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingModels = `-- name: ListEmbeddingModels :many
SELECT model,
       CAST(COUNT(*) AS INTEGER) AS docs,
       CAST(MAX(dim) AS INTEGER) AS dim
FROM embeddings
GROUP BY model
ORDER BY model
`

type ListEmbeddingModelsRow struct {
	Model string
	Docs  int64
	Dim   int64
}

func (q *Queries) ListEmbeddingModels(ctx context.Context) ([]ListEmbeddingModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingModelsRow{}
	for rows.Next() {
		var i ListEmbeddingModelsRow
		if err := rows.Scan(&i.Model, &i.Docs, &i.Dim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingMtimesByModel = `-- name: ListEmbeddingMtimesByModel :many
SELECT path, mtime_ns
FROM embeddings
WHERE model = ?
`

type ListEmbeddingMtimesByModelRow struct {
	Path    string
	MtimeNs int64
}

func (q *Queries) ListEmbeddingMtimesByModel(ctx context.Context, model string) ([]ListEmbeddingMtimesByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingMtimesByModel, model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingMtimesByModelRow{}
	for rows.Next() {
		var i ListEmbeddingMtimesByModelRow
		if err := rows.Scan(&i.Path, &i.MtimeNs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingVectorsByModel = `-- name: ListEmbeddingVectorsByModel :many
SELECT path, vec
FROM embeddings
WHERE model = ?
`

type ListEmbeddingVectorsByModelRow struct {
	Path string
	Vec  []byte
}

func (q *Queries) ListEmbeddingVectorsByModel(ctx context.Context, model string) ([]ListEmbeddingVectorsByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingVectorsByModel, model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingVectorsByModelRow{}
	for rows.Next() {
		var i ListEmbeddingVectorsByModelRow
		if err := rows.Scan(&i.Path, &i.Vec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings (path, mtime_ns, model, dim, vec)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(path, model) DO UPDATE SET
    mtime_ns = excluded.mtime_ns,
    dim      = excluded.dim,
    vec      = excluded.vec
`

type UpsertEmbeddingParams struct {
	Path    string
	MtimeNs int64
	Model   string
	Dim     int64
	Vec     []byte
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbedding,
		arg.Path,
		arg.MtimeNs,
		arg.Model,
		arg.Dim,
		arg.Vec,
	)
	return err
}

const upsertEmbeddingChunk = `-- name: UpsertEmbeddingChunk :exec
INSERT INTO embedding_chunks (path, chunk_idx, chunk_size, mtime_ns, model, dim, vec)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(path, chunk_idx, model, chunk_size) DO UPDATE SET
    mtime_ns = excluded.mtime_ns,
    dim      = excluded.dim,
    vec      = excluded.vec
`

type UpsertEmbeddingChunkParams struct {
	Path      string
	ChunkIdx  int64
	ChunkSize int64
	MtimeNs   int64
	Model     string
	Dim       int64
	Vec       []byte
}

func (q *Queries) UpsertEmbeddingChunk(ctx context.Context, arg UpsertEmbeddingChunkParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbeddingChunk,
		arg.Path,
		arg.ChunkIdx,
		arg.ChunkSize,
		arg.MtimeNs,
		arg.Model,
		arg.Dim,
		arg.Vec,
	)
	return err
}
