// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package embeddb

type Embedding struct {
	Path    string
	MtimeNs int64
	Model   string
	Dim     int64
	Vec     []byte
}

type EmbeddingChunk struct {
	Path      string
	ChunkIdx  int64
	ChunkSize int64
	MtimeNs   int64
	Model     string
	Dim       int64
	Vec       []byte
}
